layout_spectrum: 0.3707033134996891
typography_spectrum: 0.39839386311359704
color:
  saturation: 0.022822642466053367
  brandStrength: 0.02868655789643526
  rhythmicContrast: 0.38850784371607006
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  lightness: 0.3276300998404622
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6525fce5-e33b-4516-bed9-ddfc475f5679.jpg
name: missionSPACE
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3ae947a6-22fa-4b64-a08d-acd3238fbc7f.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: MissionSPACE
description: Breaking News on Space and Exploration
