typography_spectrum: 0.6381553737446666
color:
  saturation: 0.19607564597390592
  brandStrength: 0.09843032550998032
  rhythmicContrast: 0.4254860891960561
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
  lightness: 0.6735615197103471
layout_spectrum: 0.3707033134996891
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6525fce5-e33b-4516-bed9-ddfc475f5679.jpg
name: MissionSpaceCo
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3ae947a6-22fa-4b64-a08d-acd3238fbc7f.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: MissionSpaceCo
description: Breaking News on Space and Exploration
