collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5071275262162089
  brandStrength: 0.1507037489209324
  rhythmicContrast: 0.5186364601831883
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  lightness: 0.1435117635410279
typography_spectrum: 0.9072682
navigation: []
layout_spectrum: 0.5244361
name: future.s
